model:
  tmix: qwen3gdn
  attention_type: gdn # rwkv7 # rwkv7_wind_backstepping_longhead # rwkv7_wind_replaystepping_longhead # 
  mode: chunk
  expand_v: 1
  use_gate: true
  allow_neg_eigval: true
  use_short_conv: false
  conv_size: 4
  conv_bias: false
  conv_zero_init: true
  use_qk_l2norm_in_kernel: true
  use_qk_rmsnorm: true

  liger_kernel_enabled: true
  liger_patch_rms_norm: true
  liger_patch_swiglu: true
  liger_patch_rope: false
  liger_use_loss_kernels: false
