train:
  teacher:
    path: /work/yanan/data/radlads/pths/Qwen3-8B-Base/pretrained.pth
    model:
      __type__: configs.Transformer_Config
      #tmix: qwen2
      classname: qwen3
      ctx_len: 512 # 4096
      vocab_size: 151936
      vocab_padding_idx: 151646 
      num_key_value_heads: 8
      head_size: 128
      n_embd: 4096
      dim_ffn: 12288
      rms_norm_eps: 1e-6
      n_layer: 36
      rope:
          __type__: configs.RoPE_Config
          base: 1000000.0
      liger_kernel_enabled: true
      liger_patch_rms_norm: true
      liger_patch_swiglu: true
      liger_patch_rope: false
      liger_use_loss_kernels: false

