model:
  ctx_len: 512

train:
  wandb: qwen2rwkv
  
  proj_suffix: 1
  train_stage: 3
  load_partial: 1

  data_type: "binidx" 
  data_file: "/work/hei/data/dclm-10B" #data/minipile_qwen2" 
  my_exit_tokens: 300000000 # 1491785955
  # dclm-10B
  # --my_exit_tokens 1500087317 --magic_prime 5859677 --ctx_len 256
  # --my_exit_tokens 1500087317 --magic_prime 2929793 --ctx_len 512
  # --my_exit_tokens 1500087317 --magic_prime 1464917 --ctx_len 1024
  # --my_exit_tokens 1500087317 --magic_prime 732461 --ctx_len 2048
  # --my_exit_tokens 1500087317 --magic_prime 366227 --ctx_len 4096
  # --my_exit_tokens 1500087317 --magic_prime 183089 --ctx_len 8192
  # --my_exit_tokens 1500087317 --magic_prime 91541 --ctx_len 16384

  # dclm-baseline-1
  # --my_exit_tokens 100627834 --magic_prime 196523 --ctx_len 512
  # --my_exit_tokens 100627834 --magic_prime 24551 --ctx_len 4096
  # --my_exit_tokens 100627834 --magic_prime 12281 --ctx_len 8192
  # --my_exit_tokens 100627834 --magic_prime 6131 --ctx_len 16384

  # nathanctx
  # --my_exit_tokens 1565680565 --magic_prime 3057959 --ctx_len 512
  # --my_exit_tokens 1565680565 --magic_prime 1528979 --ctx_len 1024
  # --my_exit_tokens 1565680565 --magic_prime 764471 --ctx_len 2048
  # --my_exit_tokens 1565680565 --magic_prime 382241 --ctx_len 4096
  # --my_exit_tokens 1565680565 --magic_prime 191099 --ctx_len 8192
  # --my_exit_tokens 1565680565 --magic_prime 95549 --ctx_len 16384

  magic_prime: 2929793

  optimizer: dsfusedadamw
  #optimizer: adamwschedulefree
  lr_decay_type: cos
  lr_init: 1e-3
  lr_final: 1e-5
  warmup_steps: 50
  beta1: 0.9 
  beta2: 0.95
  adam_eps: 1e-8 
  weight_decay: 0

  devices: 7
  num_nodes: 1
  micro_bsz: 4
  accumulate_grad_batches: 1 # total bsz 32
  strategy: deepspeed_stage_1 #fsdp # ddp_find_unused_parameters_true # fsdp #
  grad_cp: 0
  ds_bucket_mb: 200 # set to 2 for consumer GPUs, set to 200 for A100 / H100 (affects speed & vram usage)
    
  attention_distillation_stage: 1
  epoch_save: 1
